export enum BrewType {
  FILTER = 'FILTER',
  ESPRESSO = 'ESPRESSO',
  COLD_BREW = 'COLD_BREW',
  POUR_OVER = 'POUR_OVER',
  FRENCH_PRESS = 'FRENCH_PRESS',
  AEROPRESS = 'AEROPRESS',
  SLOW_BREW = 'SLOW_BREW',
}
